buildCommand: |
  apt-get update && apt-get install -y \
    libgtk-4-1 libgraphene-1.0-0 libgstreamer-gl1.0-0 \
    gstreamer1.0-plugins-bad libenchant-2-2 libsecret-1-0 \
    libmanette-0.2-0 libgles2
  playwright install --with-deps

startCommand: bash start.sh
